# Site settings
title: Are You A Werewolf?
description: > # this means to ignore newlines until "baseurl:"
  Rules, gameplay info, and other such fun stuff for #werewolf on irc.coldfront.net.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://werewolf.drunknerds.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
